### ISSUE TITLE
Open Source Friday - Mathesar - 03-15-2024

### ISSUE THREAD

**Issue by kgodey** [githubevents/open-source-friday#34]
### Name

Kriti Godey

### GitHub Handle

@kgodey

### Project Name

Mathesar

### Project Repo

https://github.com/mathesar-foundation/mathesar

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

03-15-2024

### Twitter URL

https://twitter.com/mathesar_org

### LinkedIn URL

https://www.linkedin.com/in/kritigodey/

### Additional Information

I'd like to demo our project and use cases. I can also talk about why we chose to make Mathesar a non-profit and trying to build a sustainable open source project.

**Comment by kgodey** [comment]
@LadyKerr We're excited about this! 

I also emailed you these questions, but just in case here is better:

1. How many maintainers can join the stream? Should it just be 1 person, or can it be more? If it's just one person, could we switch to @seancolsen instead of me? @pavish is also interested in joining if multiple people can join.
2. How do we actually join the stream? The calendar invite mentions Streamyard, but I'm not sure how that works.

Thanks!

**Comment by LadyKerr** [comment]
@kgodey thanks for your questions and for sending them here! 

We prefer to have 1 person on the stream, but we can have 2 people if that's preferred, np! It can also be whoever you prefer!

I have to create/schedule the stream. Once that's done I'll send over the link in the invite and will also post here! I'll be creating the assets and such today since it's confirmed! 

Also, we always like to have a live demo. Can one be prepared?

Lemme know if you have any other questions!

**Comment by seancolsen** [comment]
Thanks @LadyKerr. I'll be managing this from here. Please switch over anything you have noted for @kgodey to me. If you need my email address, it's sean@mathesar.org.

I'll definitely be on the call. @pavish will _maybe_ be on the call — we're not sure yet.

What is the start time (and timezone) for the call? And what is the expected duration?

> we always like to have a live demo. Can one be prepared?

I'm working on this today. My plan is to run Mathesar locally on my machine and share my screen to demonstrate some of Mathesar's features. This satisfies your requirement for a "live demo", right? Or is it important that the demo be running from an Internet-accessible domain?

**Comment by LadyKerr** [comment]
@seancolsen awesome! I just added you to the cal invite. Stream is this Friday starting at 12pm central time. The stream typically runs for 30 - 45mins.

That satisfies the live demo! Folks love to see the project in action and you can also screen share the repo and any issues you need help with and such. Here is the link to [some prep instructions](https://gist.github.com/LadyKerr/9b7d6dccde55b3f30398612d1290b7dc)

I will be creating assets today and will add your photo for the promo since we're unsure Pavish will be oon the call.
Let me know if you have anymore questions.

**Comment by kgodey** [comment]
Thanks @LadyKerr, and sorry for any inconvenience caused by switching from me to @seancolsen.

**Comment by LadyKerr** [comment]
![osf-mathesar](https://github.com/githubevents/open-source-friday/assets/47188731/f05d6cf4-f0af-4da1-a5c6-3d48d034249b)

**Comment by seancolsen** [comment]
@LadyKerr I'm looking forward to this today. It will just be me.

I see you said:

> I'll send over the link in the invite and will also post here!

I have the event in my calendar, but I still don't see any link in it that seems like it would allow me to join the call. 

How do I join the call? Will you be sending me a link? Thanks!

**Comment by LadyKerr** [comment]
Oh yes! Here is the link: https://streamyard.com/j6siaces5e 

please join at 12:45! est
